name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: ap-south-1
  ACCOUNT_ID: 238395401573
  IMAGE_NAME: myapp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::238395401573:role/github-actions-ecr-push
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Tag Docker Image
        run: |
          docker tag \
          $IMAGE_NAME:${{ github.sha }} \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:${{ github.sha }}

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: cyclonedx-json
          output-file: sbom.cdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.cdx.json

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign Docker Image
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign --yes \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:${{ github.sha }}

      - name: Verify Signature
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign verify \
            --certificate-identity-regexp "https://github.com/VSaiSuneeth/myapp/.github/workflows/deploy.yml@refs/heads/main" \
            --certificate-oidc-issuer https://token.actions.githubusercontent.com \
            $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:${{ github.sha }}

      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: VSaiSuneeth/myapp-gitops
          ssh-key: ${{ secrets.GITOPS_DEPLOY_KEY }}
          persist-credentials: false
          path: gitops

      - name: Update Helm Chart
        run: |
          sed -i "s|repository:.*|repository: $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME|g" gitops/myapp-chart/values.yaml
          sed -i "s|tag:.*|tag: \"${{ github.sha }}\"|g" gitops/myapp-chart/values.yaml

      - name: Commit and Push GitOps Changes
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add myapp-chart/values.yaml

          git diff --cached --quiet || git commit -m "Update image tag to ${{ github.sha }}"

          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          git push origin main